### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by MatheusBordin** [kambojajs/kamboja#52]
Hello! I am using this framework in a college project and need to configure the CORS of my application. How can I do this?

**Comment by ktutnik** [comment]
Finally a first user yeey! :)

Currently there is no way to write to response header now. Im working on it and it will be easy.

so the spec will allow KambojaJS to add response header below:

```
"Access-Control-Allow-Origin", "*"
"Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept"
```

The implementation will be a single decorator named @cors()

```typescript
@cors() //class scoped
export class MyController {
     
     //or can be specified in action
     @cors()
     index(){
     }
}
```

Do you have additional thought?

Note: The API of KambojaJS will be changed frequently until i'm happy with the version 0.1.0 (eta next 2 weeks).

**Comment by MatheusBordin** [comment]
Hello! Unfortunately I need to do this type of implementation today, the project is for next week, is there any hotfix?

**Comment by ktutnik** [comment]
Just to be clear, what version did you use for `kamboja` and `kamboja-express` ? I will examine if it can be hack somewhere.

The hot fix can't be push today because it is in a core module will impact other function and might cause some fail unit tests.

**Comment by ktutnik** [comment]
**Note this is just a hack, on next version of KambojaJS will support writing response header from ActionResult easily done in controller/middlewares**

I assume you are using the `kamboja-cli` with `starter basic` so your kamboja and kamboja-express version is:
```
"kamboja": "0.0.1-43",
"kamboja-express": "0.0.1-31",
```

I have tried some experiment and i think you can provide instance of express application on the express engine. Then create a global express middleware to send the http header.


```typescript
import { Kamboja, Core } from "kamboja"
import { ExpressEngine } from "kamboja-express"
import * as Express from "express"
import * as BodyParser from "body-parser"

//do something like this
//http://stackoverflow.com/a/14172431/212706

//create an express application
//setup other middlewares required.
let express = Express()
express.use(BodyParser.json())
//define a global express middleware and override the header
express.use((req, resp, next) => {
    resp.setHeader("Access-Control-Allow-Origin", "*");
    next()
})
//pass the express app to the engine
let engine = new ExpressEngine(express)
let kamboja = new Kamboja(engine, {
    rootPath: __dirname
});

let app = kamboja.init()
export { app }
```

I tried above code and it returns the header properly
![Alt text](https://monosnap.com/file/oBs1BM2knRNuTFTCnjT1mCChIr2w6A.png)

**Comment by MatheusBordin** [comment]
Hi, I already tried this solution and it worked perfectly! Thank you.
